import './globals.css';
import type { Metadata } from 'next';

import Navbar from './components/NavBar/NavBar';
import Cursor from './components/NavBar/Cursor';

export const metadata: Metadata = {
    title: 'Somewhere',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
